name: 'Push directory to another repository'
description: 'Useful to push files to another repository to be used, for example, via github pages'
inputs:
  token:
    description: 'Github token for this action (you have to create this in your settings).'
    required: true
  source_file_path:
    description: '"Path" to generated file. Ex: path/to/file.md'
    required: true
  destination_repo:
    description: 'Repository to push file to.'
    required: true
  destination_folder:
    description: 'Folder to push to in destination repository.'
    required: true
  target_branch:
    description: '[Optional] set target branch name for the destination repository. Default is "main".'
    required: false
  author:
    description: "[Optional] Name of the commit's author. Default is user name of account doing action."
    required: false
  author_email:
    description: '[Optional] Email for the git commit. Default is author@no-reply...'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'git-commit'
  color: 'green'
